version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news_web
        volumes:
            - db_volume:/app/db
            - static_volume:/volumetmp
            - media_volume:/app/media
        env_file:
          - .env
        ports:
            - 8000:8000
        command: ["/bin/sh", "-c", "rm -rf /volumetmp/* && cp -r /app/static/* /volumetmp/ && gunicorn DutchNewsWeb.wsgi:application --bind 0.0.0.0:8000"]


    nginx:
        image: nginx:1.19.0-alpine
        container_name: news_nginx
        ports:
          - "80:80"
        volumes:
          - ./nginx:/etc/nginx/conf.d
          - static_volume:/app/static
          - media_volume:/app/media
        depends_on:
            - web
        command: nginx -g 'daemon off;'


    redis:
      image: "redis:latest"
      container_name: news_redis
      ports:
        - "6379:6379"

    celery_worker:
      build: .
      container_name: news_celery_worker
      command: celery -A DutchNewsWeb worker --loglevel=info
      volumes:
        - .:/code
        - db_volume:/app/db
        - media_volume:/app/media
      env_file:
        - .env
      depends_on:
        - redis

    celery_beat:
      build: .
      container_name: news_celery_beat
      command: celery -A DutchNewsWeb beat --loglevel=info
      volumes:
        - .:/code
      env_file:
        - .env
      depends_on:
        - redis


volumes:
     static_volume:
     media_volume:
     db_volume: